#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apt"
cookbook "chef-server"
cookbook "sudo"
cookbook "ubuntu"
cookbook "users"
cookbook "zsh"

my_cookbooks = %w{
    node-build-agent
    node-uptime
    staging
    teamcity
    vyacheslav-dotfiles
}

my_cookbooks.each do |my_cookbook|
    cookbook my_cookbook, :path => "my_cookbooks/#{my_cookbook}"
end
