#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

%w{ apt teamcity_server chef-server ubuntu vslinko youtrack }.each do |cb|
  cookbook cb
end

rithis_cookbooks = %w{
  teamcity_build_agent
  teamcity_server
  youtrack
}

rithis_cookbooks.each do |suffix|
  cookbook "rithis_#{suffix}", :path => "rithis/#{suffix}"
end
